import { SEOPage } from '@/types';

export const seoPages: SEOPage[] = [
  {
    slug: 'download-instagram-reels',
    title: 'Download Instagram Reels',
    metaTitle: 'Download Instagram Reels Online Free - HD Quality | QuicklySave',
    metaDescription: 'Download Instagram Reels online for free in HD quality. The fastest and easiest way to save Instagram Reels to your device.',
    heading: 'Download Instagram Reels Online',
    subheading: 'The fastest free tool to save Instagram Reels in HD quality. No login required.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['download instagram reels', 'save instagram reels', 'instagram reel downloader'],
  },
  {
    slug: 'download-youtube-video',
    title: 'Download YouTube Video',
    metaTitle: 'Download YouTube Video Online Free - HD/4K | QuicklySave',
    metaDescription: 'Download YouTube videos online for free in HD and 4K quality. Save any YouTube video for offline viewing.',
    heading: 'Download YouTube Video Online',
    subheading: 'Save any YouTube video in HD or 4K quality. Fast, free, and no registration needed.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['download youtube video', 'youtube video download', 'save youtube video'],
  },
  {
    slug: 'download-tiktok-video',
    title: 'Download TikTok Video',
    metaTitle: 'Download TikTok Video Online Free - HD Quality | QuicklySave',
    metaDescription: 'Download TikTok videos online for free in HD quality. Save any TikTok to your phone or computer instantly.',
    heading: 'Download TikTok Video Online',
    subheading: 'Save TikTok videos in HD quality. Free, fast, and works on all devices.',
    toolSlug: 'tiktok-video-downloader',
    keywords: ['download tiktok video', 'tiktok video download', 'save tiktok video'],
  },
  {
    slug: 'save-instagram-reels',
    title: 'Save Instagram Reels',
    metaTitle: 'Save Instagram Reels to Phone & PC Free | QuicklySave',
    metaDescription: 'Save Instagram Reels to your phone or PC for free. Download Reels in original HD quality with one click.',
    heading: 'Save Instagram Reels to Your Device',
    subheading: 'One-click solution to save any Instagram Reel to your phone or computer in HD.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['save instagram reels', 'save reels to phone', 'save instagram reels to gallery'],
  },
  {
    slug: 'youtube-video-download-online',
    title: 'YouTube Video Download Online',
    metaTitle: 'YouTube Video Download Online Free - No Software | QuicklySave',
    metaDescription: 'Download YouTube videos online without installing any software. Free HD video downloads from YouTube.',
    heading: 'YouTube Video Download Online',
    subheading: 'No software needed. Download YouTube videos directly from your browser for free.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['youtube video download online', 'online youtube downloader', 'youtube download free'],
  },
  {
    slug: 'tiktok-download-without-watermark',
    title: 'TikTok Download Without Watermark',
    metaTitle: 'TikTok Download Without Watermark Free - HD | QuicklySave',
    metaDescription: 'Download TikTok videos without watermark in HD quality. Get clean TikTok videos for free with QuicklySave.',
    heading: 'Download TikTok Without Watermark',
    subheading: 'Get clean TikTok videos without the watermark. HD quality, completely free.',
    toolSlug: 'tiktok-no-watermark-downloader',
    keywords: ['tiktok download without watermark', 'tiktok no watermark', 'remove tiktok watermark'],
  },
  {
    slug: 'free-instagram-video-downloader',
    title: 'Free Instagram Video Downloader',
    metaTitle: 'Free Instagram Video Downloader Online - HD | QuicklySave',
    metaDescription: 'Free Instagram video downloader. Save Instagram videos in HD quality without any cost or registration.',
    heading: 'Free Instagram Video Downloader',
    subheading: 'Download Instagram videos for free. No registration, no limits, HD quality.',
    toolSlug: 'instagram-video-downloader',
    keywords: ['free instagram video downloader', 'instagram video download free', 'free ig downloader'],
  },
  {
    slug: 'hd-video-downloader-online',
    title: 'HD Video Downloader Online',
    metaTitle: 'HD Video Downloader Online Free - All Platforms | QuicklySave',
    metaDescription: 'Download HD videos from Instagram, YouTube, TikTok, Twitter, and Facebook. Free online HD video downloader.',
    heading: 'HD Video Downloader Online',
    subheading: 'Download HD videos from all major social media platforms. Fast, free, and easy.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['hd video downloader', 'hd video download online', 'free hd downloader'],
  },
  {
    slug: 'twitter-video-download-free',
    title: 'Twitter Video Download Free',
    metaTitle: 'Twitter/X Video Download Free Online - HD | QuicklySave',
    metaDescription: 'Download Twitter/X videos for free in HD quality. Save any tweet video or GIF to your device online.',
    heading: 'Download Twitter Videos Free',
    subheading: 'Save Twitter/X videos and GIFs to your device. Free, fast, and in HD quality.',
    toolSlug: 'twitter-video-downloader',
    keywords: ['twitter video download', 'download tweet video', 'x video download free'],
  },
  {
    slug: 'facebook-video-download-free',
    title: 'Facebook Video Download Free',
    metaTitle: 'Facebook Video Download Free Online - HD | QuicklySave',
    metaDescription: 'Download Facebook videos for free in HD quality. Save any Facebook video to your device online.',
    heading: 'Download Facebook Videos Free',
    subheading: 'Save Facebook videos and Reels to your device. Free, fast, and in HD quality.',
    toolSlug: 'facebook-video-downloader',
    keywords: ['facebook video download', 'download fb video', 'facebook video download free'],
  },
  {
    slug: 'youtube-to-mp3-converter-free',
    title: 'YouTube to MP3 Converter Free',
    metaTitle: 'YouTube to MP3 Converter Free Online - 320kbps | QuicklySave',
    metaDescription: 'Convert YouTube videos to MP3 for free. High-quality 320kbps audio conversion online.',
    heading: 'Free YouTube to MP3 Converter',
    subheading: 'Convert any YouTube video to high-quality MP3 audio. Free and instant.',
    toolSlug: 'youtube-to-mp3',
    keywords: ['youtube to mp3', 'youtube mp3 converter', 'convert youtube to mp3 free'],
  },
  {
    slug: 'instagram-reel-saver',
    title: 'Instagram Reel Saver',
    metaTitle: 'Instagram Reel Saver - Save Reels to Gallery Free | QuicklySave',
    metaDescription: 'Save Instagram Reels to your gallery or camera roll. Free Instagram Reel saver tool online.',
    heading: 'Instagram Reel Saver',
    subheading: 'Save any Instagram Reel directly to your gallery. Free and instant.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['instagram reel saver', 'save reel to gallery', 'instagram reel save online'],
  },
  {
    slug: 'social-media-video-downloader',
    title: 'Social Media Video Downloader',
    metaTitle: 'Social Media Video Downloader - All Platforms Free | QuicklySave',
    metaDescription: 'Download videos from all social media platforms. Instagram, YouTube, TikTok, Twitter, Facebook. Free online tool.',
    heading: 'Social Media Video Downloader',
    subheading: 'One tool for all platforms. Download videos from Instagram, YouTube, TikTok, Twitter, and Facebook.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['social media video downloader', 'download social media video', 'all in one downloader'],
  },
  {
    slug: 'free-video-downloader-online',
    title: 'Free Video Downloader Online',
    metaTitle: 'Free Video Downloader Online - All Social Media | QuicklySave',
    metaDescription: 'Free online video downloader for all social media platforms. Download HD videos without registration.',
    heading: 'Free Video Downloader Online',
    subheading: 'Download videos from any social media platform for free. No registration needed.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['free video downloader', 'video downloader online', 'download video free'],
  },
  {
    slug: 'instagram-audio-downloader',
    title: 'Instagram Audio Downloader',
    metaTitle: 'Instagram Audio Downloader - Extract Audio MP3 | QuicklySave',
    metaDescription: 'Download audio from Instagram Reels and videos. Extract and save audio as MP3 files for free.',
    heading: 'Instagram Audio Downloader',
    subheading: 'Extract audio from Instagram videos and Reels. Save as high-quality MP3.',
    toolSlug: 'instagram-audio-extractor',
    keywords: ['instagram audio downloader', 'instagram audio extract', 'instagram to mp3'],
  },
];

export function getSEOPageBySlug(slug: string): SEOPage | undefined {
  return seoPages.find((p) => p.slug === slug);
}
