import { SEOPage } from '@/types';

export const seoPages: SEOPage[] = [

  // ─── INSTAGRAM REELS ────────────────────────────────────────────────────────
  {
    slug: 'download-instagram-reels',
    title: 'Download Instagram Reels',
    metaTitle: 'Download Instagram Reels Online Free - HD Quality | QuicklySave',
    metaDescription: 'Download Instagram Reels online for free in HD quality. The fastest way to save Instagram Reels to your device instantly.',
    heading: 'Download Instagram Reels Online',
    subheading: 'The fastest free tool to save Instagram Reels in HD quality. No login required.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['download instagram reels', 'save instagram reels', 'instagram reel downloader'],
  },
  {
    slug: 'save-instagram-reels',
    title: 'Save Instagram Reels',
    metaTitle: 'Save Instagram Reels to Phone & PC Free | QuicklySave',
    metaDescription: 'Save Instagram Reels to your phone or PC for free. Download Reels in original HD quality with one click.',
    heading: 'Save Instagram Reels to Your Device',
    subheading: 'One-click solution to save any Instagram Reel to your phone or computer in HD.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['save instagram reels', 'save reels to phone', 'save instagram reels to gallery'],
  },
  {
    slug: 'instagram-reel-saver',
    title: 'Instagram Reel Saver',
    metaTitle: 'Instagram Reel Saver - Save Reels to Gallery Free | QuicklySave',
    metaDescription: 'Save Instagram Reels to your gallery or camera roll for free. The best Instagram Reel saver tool online.',
    heading: 'Instagram Reel Saver',
    subheading: 'Save any Instagram Reel directly to your gallery. Free and instant.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['instagram reel saver', 'save reel to gallery', 'instagram reel save online'],
  },
  {
    slug: 'insta-reels-download',
    title: 'Insta Reels Download',
    metaTitle: 'Insta Reels Download Free Online - HD | QuicklySave',
    metaDescription: 'Download Insta Reels free online in HD quality. Paste the reel link and save instantly to any device.',
    heading: 'Insta Reels Download',
    subheading: 'Paste any Instagram Reel link and download it instantly. Free, fast, HD quality.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['insta reels download', 'insta reel download online', 'download reels from instagram'],
  },
  {
    slug: 'instagram-reels-download-online',
    title: 'Instagram Reels Download Online',
    metaTitle: 'Instagram Reels Download Online Free No App | QuicklySave',
    metaDescription: 'Download Instagram Reels online without any app or software. Free HD Instagram Reel downloader — works on iPhone, Android, PC.',
    heading: 'Instagram Reels Download Online – No App Needed',
    subheading: 'Works directly in your browser. No app, no login, completely free.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['instagram reels download online', 'download instagram reels without app', 'online instagram reel saver'],
  },
  {
    slug: 'instagram-reels-downloader-without-watermark',
    title: 'Instagram Reels Downloader Without Watermark',
    metaTitle: 'Instagram Reels Downloader Without Watermark Free | QuicklySave',
    metaDescription: 'Download Instagram Reels without any watermark. Get clean HD videos free using QuicklySave.',
    heading: 'Instagram Reels Downloader Without Watermark',
    subheading: 'Clean downloads — no watermarks, no logos, pure HD video.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['instagram reels downloader without watermark', 'download reels no watermark', 'clean instagram reel download'],
  },
  {
    slug: 'instagram-reels-download-iphone',
    title: 'Instagram Reels Download iPhone',
    metaTitle: 'Download Instagram Reels on iPhone Free - iOS Safari | QuicklySave',
    metaDescription: 'Download Instagram Reels on iPhone and iPad for free. No app needed — works directly in Safari on iOS.',
    heading: 'Download Instagram Reels on iPhone',
    subheading: 'Easily save Instagram Reels on iOS. Works in Safari — no app install required.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['instagram reels download iphone', 'save instagram reels iphone', 'download reels on ios'],
  },
  {
    slug: 'instagram-reels-download-android',
    title: 'Instagram Reels Download Android',
    metaTitle: 'Download Instagram Reels on Android Free | QuicklySave',
    metaDescription: 'Download Instagram Reels on Android phones and tablets. Free, no app needed, HD quality.',
    heading: 'Download Instagram Reels on Android',
    subheading: 'Save any Instagram Reel to your Android device in HD. Free and instant.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['instagram reels download android', 'save instagram reels android', 'android instagram reel downloader'],
  },
  {
    slug: 'instagram-reels-video-download',
    title: 'Instagram Reels Video Download',
    metaTitle: 'Instagram Reels Video Download Free HD | QuicklySave',
    metaDescription: 'Download Instagram Reels videos for free in HD. Save any Instagram Reel video online with one click.',
    heading: 'Instagram Reels Video Download',
    subheading: 'Save Reels videos in full HD quality. Fast, free, no registration.',
    toolSlug: 'instagram-reels-downloader',
    keywords: ['instagram reels video download', 'download reel video instagram', 'instagram video reel save'],
  },

  // ─── INSTAGRAM VIDEO ────────────────────────────────────────────────────────
  {
    slug: 'free-instagram-video-downloader',
    title: 'Free Instagram Video Downloader',
    metaTitle: 'Free Instagram Video Downloader Online - HD | QuicklySave',
    metaDescription: 'Free Instagram video downloader. Save Instagram videos in HD quality without any cost or registration.',
    heading: 'Free Instagram Video Downloader',
    subheading: 'Download Instagram videos for free. No registration, no limits, HD quality.',
    toolSlug: 'instagram-video-downloader',
    keywords: ['free instagram video downloader', 'instagram video download free', 'free ig downloader'],
  },
  {
    slug: 'instagram-video-download',
    title: 'Instagram Video Download',
    metaTitle: 'Instagram Video Download Online Free HD | QuicklySave',
    metaDescription: 'Download Instagram videos online for free. Save any Instagram post video in HD quality instantly.',
    heading: 'Instagram Video Download',
    subheading: 'Download any Instagram video post instantly. Free HD quality downloads.',
    toolSlug: 'instagram-video-downloader',
    keywords: ['instagram video download', 'download instagram video', 'ig video downloader'],
  },
  {
    slug: 'download-instagram-video-online',
    title: 'Download Instagram Video Online',
    metaTitle: 'Download Instagram Video Online Free No Login | QuicklySave',
    metaDescription: 'Download Instagram videos online without login. Free Instagram video downloader — paste link and save.',
    heading: 'Download Instagram Video Online',
    subheading: 'Paste the Instagram video link and save it instantly. No login required.',
    toolSlug: 'instagram-video-downloader',
    keywords: ['download instagram video online', 'online instagram video downloader', 'instagram video save online'],
  },
  {
    slug: 'instagram-photo-download',
    title: 'Instagram Photo Download',
    metaTitle: 'Instagram Photo Download Online Free Full Resolution | QuicklySave',
    metaDescription: 'Download Instagram photos in full resolution for free. Save any Instagram image online instantly.',
    heading: 'Instagram Photo Download',
    subheading: 'Save Instagram photos in original full resolution. Free and instant.',
    toolSlug: 'instagram-photo-downloader',
    keywords: ['instagram photo download', 'download instagram photo', 'save instagram photo'],
  },
  {
    slug: 'instagram-audio-downloader',
    title: 'Instagram Audio Downloader',
    metaTitle: 'Instagram Audio Downloader - Extract Audio MP3 Free | QuicklySave',
    metaDescription: 'Download audio from Instagram Reels and videos. Extract and save audio as MP3 files for free.',
    heading: 'Instagram Audio Downloader',
    subheading: 'Extract audio from Instagram videos and Reels. Save as high-quality MP3.',
    toolSlug: 'instagram-audio-extractor',
    keywords: ['instagram audio downloader', 'instagram audio extract', 'instagram to mp3'],
  },
  {
    slug: 'instagram-to-mp3',
    title: 'Instagram to MP3',
    metaTitle: 'Instagram to MP3 Converter Free Online | QuicklySave',
    metaDescription: 'Convert Instagram Reels and videos to MP3 audio for free. Extract high-quality audio from any Instagram video.',
    heading: 'Instagram to MP3 Converter',
    subheading: 'Extract MP3 audio from any Instagram Reel or video. Free, fast, high quality.',
    toolSlug: 'instagram-audio-extractor',
    keywords: ['instagram to mp3', 'instagram mp3 download', 'extract audio instagram'],
  },
  {
    slug: 'instagram-story-downloader',
    title: 'Instagram Story Downloader',
    metaTitle: 'Instagram Story Downloader Free Online | QuicklySave',
    metaDescription: 'Download Instagram Stories for free. Save Instagram Story videos and photos online.',
    heading: 'Instagram Story Downloader',
    subheading: 'Save Instagram Stories to your device. Free, fast, no login needed.',
    toolSlug: 'instagram-video-downloader',
    keywords: ['instagram story downloader', 'download instagram story', 'save instagram story'],
  },

  // ─── YOUTUBE VIDEO ──────────────────────────────────────────────────────────
  {
    slug: 'youtube-video-download-online',
    title: 'YouTube Video Download Online',
    metaTitle: 'YouTube Video Download Online Free - No Software | QuicklySave',
    metaDescription: 'Download YouTube videos online without installing any software. Free HD video downloads from YouTube.',
    heading: 'YouTube Video Download Online',
    subheading: 'No software needed. Download YouTube videos directly from your browser for free.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['youtube video download online', 'online youtube downloader', 'youtube download free'],
  },
  {
    slug: 'download-youtube-video',
    title: 'Download YouTube Video',
    metaTitle: 'Download YouTube Video Online Free - HD/4K | QuicklySave',
    metaDescription: 'Download YouTube videos online for free in HD and 4K quality. Save any YouTube video for offline viewing.',
    heading: 'Download YouTube Video Online',
    subheading: 'Save any YouTube video in HD or 4K quality. Fast, free, and no registration needed.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['download youtube video', 'youtube video download', 'save youtube video'],
  },
  {
    slug: 'youtube-video-downloader-free',
    title: 'YouTube Video Downloader Free',
    metaTitle: 'YouTube Video Downloader Free Online HD 4K | QuicklySave',
    metaDescription: 'Free YouTube video downloader — download any YouTube video in HD, Full HD or 4K. No registration, no limits.',
    heading: 'YouTube Video Downloader Free',
    subheading: 'Download any YouTube video for free. HD, Full HD, 4K — pick your quality.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['youtube video downloader free', 'free youtube downloader', 'youtube download hd free'],
  },
  {
    slug: 'youtube-downloader-hd',
    title: 'YouTube Downloader HD',
    metaTitle: 'YouTube Downloader HD - Download YouTube Videos 1080p 4K | QuicklySave',
    metaDescription: 'Download YouTube videos in HD quality — 720p, 1080p, 1440p and 4K. Free online YouTube HD downloader.',
    heading: 'YouTube Downloader HD',
    subheading: 'Save YouTube videos in Full HD 1080p, 1440p, and 4K. Free and instant.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['youtube downloader hd', 'youtube hd download', 'download youtube 1080p', 'download youtube 4k'],
  },
  {
    slug: 'youtube-video-download-1080p',
    title: 'YouTube Video Download 1080p',
    metaTitle: 'YouTube Video Download 1080p Free Full HD | QuicklySave',
    metaDescription: 'Download YouTube videos in 1080p Full HD for free. Save YouTube videos in the best quality.',
    heading: 'YouTube Video Download 1080p HD',
    subheading: 'Download YouTube videos in crystal clear 1080p Full HD. Free, no quality loss.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['youtube video download 1080p', 'download youtube 1080p', 'youtube 1080p downloader'],
  },
  {
    slug: 'youtube-video-download-mp4',
    title: 'YouTube Video Download MP4',
    metaTitle: 'YouTube Video Download MP4 Free Online | QuicklySave',
    metaDescription: 'Download YouTube videos in MP4 format for free. Save any YouTube video as MP4 in HD quality.',
    heading: 'Download YouTube Videos in MP4',
    subheading: 'Save YouTube videos as MP4 files. Compatible with all devices and players.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['youtube video download mp4', 'download youtube as mp4', 'youtube mp4 downloader'],
  },
  {
    slug: 'youtube-shorts-download',
    title: 'YouTube Shorts Download',
    metaTitle: 'YouTube Shorts Download Free Online HD | QuicklySave',
    metaDescription: 'Download YouTube Shorts videos for free in HD quality. Save any YouTube Short to your device online.',
    heading: 'YouTube Shorts Download',
    subheading: 'Download any YouTube Short video instantly. Free HD quality, no app needed.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['youtube shorts download', 'download youtube shorts', 'save youtube short video'],
  },
  {
    slug: 'youtube-shorts-downloader',
    title: 'YouTube Shorts Downloader',
    metaTitle: 'YouTube Shorts Downloader Free Online | QuicklySave',
    metaDescription: 'Free YouTube Shorts downloader. Save any YouTube Short video online without any app.',
    heading: 'YouTube Shorts Downloader',
    subheading: 'Download YouTube Shorts in seconds. Free, no login, HD quality.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['youtube shorts downloader', 'youtube shorts download online', 'yt shorts downloader'],
  },
  {
    slug: 'youtube-video-save-online',
    title: 'Save YouTube Video Online',
    metaTitle: 'Save YouTube Video Online Free No App | QuicklySave',
    metaDescription: 'Save YouTube videos online for free without any app or extension. Works on all devices instantly.',
    heading: 'Save YouTube Videos Online',
    subheading: 'Save any YouTube video directly from your browser. Free, no software needed.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['save youtube video online', 'save youtube video free', 'youtube video save'],
  },

  // ─── YOUTUBE MP3 ────────────────────────────────────────────────────────────
  {
    slug: 'youtube-to-mp3',
    title: 'YouTube to MP3',
    metaTitle: 'YouTube to MP3 Converter Free Online 320kbps | QuicklySave',
    metaDescription: 'Convert YouTube to MP3 for free in 320kbps high quality. The fastest YouTube to MP3 converter online.',
    heading: 'YouTube to MP3 Converter',
    subheading: 'Convert any YouTube video to high-quality MP3. Free, fast, 320kbps.',
    toolSlug: 'youtube-to-mp3',
    keywords: ['youtube to mp3', 'youtube mp3 converter', 'convert youtube to mp3'],
  },
  {
    slug: 'youtube-to-mp3-converter-free',
    title: 'YouTube to MP3 Converter Free',
    metaTitle: 'YouTube to MP3 Converter Free Online - High Quality | QuicklySave',
    metaDescription: 'Convert YouTube videos to MP3 for free. High-quality 320kbps audio conversion online.',
    heading: 'Free YouTube to MP3 Converter',
    subheading: 'Convert any YouTube video to high-quality MP3 audio. Free and instant.',
    toolSlug: 'youtube-to-mp3',
    keywords: ['youtube to mp3 converter free', 'youtube mp3 download free', 'free youtube to mp3'],
  },
  {
    slug: 'youtube-mp3-download',
    title: 'YouTube MP3 Download',
    metaTitle: 'YouTube MP3 Download Free Online High Quality | QuicklySave',
    metaDescription: 'Download YouTube videos as MP3 audio files for free. Fast, high-quality YouTube MP3 downloader online.',
    heading: 'YouTube MP3 Download',
    subheading: 'Extract and download MP3 audio from any YouTube video. Free and instant.',
    toolSlug: 'youtube-to-mp3',
    keywords: ['youtube mp3 download', 'download youtube mp3', 'youtube audio download'],
  },
  {
    slug: 'youtube-video-to-mp3',
    title: 'YouTube Video to MP3',
    metaTitle: 'YouTube Video to MP3 Converter Free Online | QuicklySave',
    metaDescription: 'Convert YouTube video to MP3 audio online for free. Paste the YouTube URL and get your MP3 instantly.',
    heading: 'Convert YouTube Video to MP3',
    subheading: 'Turn any YouTube video into an MP3 file in seconds. 100% free.',
    toolSlug: 'youtube-to-mp3',
    keywords: ['youtube video to mp3', 'convert youtube video to mp3', 'youtube to audio'],
  },
  {
    slug: 'yt-to-mp3',
    title: 'YT to MP3',
    metaTitle: 'YT to MP3 Converter Free Online - Fast & Easy | QuicklySave',
    metaDescription: 'Convert YT to MP3 for free. Fastest YT MP3 converter online — paste URL and download instantly.',
    heading: 'YT to MP3 Converter',
    subheading: 'The fastest way to convert YT videos to MP3. Free, instant, high quality.',
    toolSlug: 'youtube-to-mp3',
    keywords: ['yt to mp3', 'yt mp3 converter', 'yt mp3 download free'],
  },
  {
    slug: 'youtube-audio-download',
    title: 'YouTube Audio Download',
    metaTitle: 'YouTube Audio Download Free Online MP3 | QuicklySave',
    metaDescription: 'Download audio from any YouTube video for free. Save YouTube audio as MP3 in high quality.',
    heading: 'YouTube Audio Download',
    subheading: 'Extract and save audio from any YouTube video. Free MP3 downloads.',
    toolSlug: 'youtube-to-mp3',
    keywords: ['youtube audio download', 'download audio from youtube', 'youtube extract audio'],
  },
  {
    slug: 'youtube-music-download',
    title: 'YouTube Music Download',
    metaTitle: 'YouTube Music Download Free MP3 Online | QuicklySave',
    metaDescription: 'Download music from YouTube for free as MP3. Save any YouTube music video as audio.',
    heading: 'YouTube Music Download',
    subheading: 'Save music from YouTube as MP3 audio. Free, fast, high quality.',
    toolSlug: 'youtube-to-mp3',
    keywords: ['youtube music download', 'download music from youtube', 'youtube music mp3'],
  },

  // ─── TIKTOK ─────────────────────────────────────────────────────────────────
  {
    slug: 'download-tiktok-video',
    title: 'Download TikTok Video',
    metaTitle: 'Download TikTok Video Online Free - HD Quality | QuicklySave',
    metaDescription: 'Download TikTok videos online for free in HD quality. Save any TikTok to your phone or computer instantly.',
    heading: 'Download TikTok Video Online',
    subheading: 'Save TikTok videos in HD quality. Free, fast, and works on all devices.',
    toolSlug: 'tiktok-video-downloader',
    keywords: ['download tiktok video', 'tiktok video download', 'save tiktok video'],
  },
  {
    slug: 'tiktok-download-without-watermark',
    title: 'TikTok Download Without Watermark',
    metaTitle: 'TikTok Download Without Watermark Free HD | QuicklySave',
    metaDescription: 'Download TikTok videos without watermark in HD quality. Get clean TikTok videos for free with QuicklySave.',
    heading: 'Download TikTok Without Watermark',
    subheading: 'Get clean TikTok videos without the watermark. HD quality, completely free.',
    toolSlug: 'tiktok-no-watermark-downloader',
    keywords: ['tiktok download without watermark', 'tiktok no watermark', 'remove tiktok watermark'],
  },
  {
    slug: 'tiktok-video-download-no-watermark',
    title: 'TikTok Video Download No Watermark',
    metaTitle: 'TikTok Video Download No Watermark Free Online | QuicklySave',
    metaDescription: 'Download TikTok videos without watermark for free. Save clean HD TikTok videos online instantly.',
    heading: 'TikTok Video Download No Watermark',
    subheading: 'Remove the TikTok watermark and download clean videos in HD. Free and instant.',
    toolSlug: 'tiktok-no-watermark-downloader',
    keywords: ['tiktok video download no watermark', 'tiktok no watermark download', 'clean tiktok video'],
  },
  {
    slug: 'tiktok-video-downloader-online',
    title: 'TikTok Video Downloader Online',
    metaTitle: 'TikTok Video Downloader Online Free No App | QuicklySave',
    metaDescription: 'Download TikTok videos online without any app. Free TikTok downloader — works on all browsers and devices.',
    heading: 'TikTok Video Downloader Online',
    subheading: 'Download TikTok videos from any browser. No app, no registration, completely free.',
    toolSlug: 'tiktok-video-downloader',
    keywords: ['tiktok video downloader online', 'online tiktok downloader', 'tiktok download browser'],
  },
  {
    slug: 'save-tiktok-video',
    title: 'Save TikTok Video',
    metaTitle: 'Save TikTok Video to Phone Free HD | QuicklySave',
    metaDescription: 'Save TikTok videos to your phone or PC for free. Download TikTok HD videos with one click.',
    heading: 'Save TikTok Video to Phone',
    subheading: 'Save any TikTok video directly to your device. Free, fast, HD quality.',
    toolSlug: 'tiktok-video-downloader',
    keywords: ['save tiktok video', 'save tiktok to phone', 'tiktok video save'],
  },
  {
    slug: 'tiktok-mp3-download',
    title: 'TikTok MP3 Download',
    metaTitle: 'TikTok MP3 Download Free Online - Extract TikTok Audio | QuicklySave',
    metaDescription: 'Download TikTok audio as MP3 for free. Extract and save audio from any TikTok video online.',
    heading: 'TikTok MP3 Download',
    subheading: 'Extract and download audio from any TikTok as MP3. Free and instant.',
    toolSlug: 'tiktok-video-downloader',
    keywords: ['tiktok mp3 download', 'download tiktok audio', 'tiktok audio mp3'],
  },
  {
    slug: 'tiktok-downloader-hd',
    title: 'TikTok Downloader HD',
    metaTitle: 'TikTok Downloader HD Free Online Full Quality | QuicklySave',
    metaDescription: 'Download TikTok videos in HD quality for free. Save TikTok videos in full original resolution.',
    heading: 'TikTok Downloader HD',
    subheading: 'Save TikTok videos in full HD resolution. Free, no watermark, instant download.',
    toolSlug: 'tiktok-video-downloader',
    keywords: ['tiktok downloader hd', 'tiktok hd download', 'download tiktok in hd'],
  },
  {
    slug: 'tiktok-video-save-online',
    title: 'Save TikTok Video Online',
    metaTitle: 'Save TikTok Video Online Free No Watermark | QuicklySave',
    metaDescription: 'Save TikTok videos online for free without watermark. Works on iPhone, Android, and PC.',
    heading: 'Save TikTok Video Online',
    subheading: 'Online TikTok saver — no watermark, no app, completely free.',
    toolSlug: 'tiktok-no-watermark-downloader',
    keywords: ['save tiktok video online', 'tiktok online saver', 'tiktok save without watermark online'],
  },

  // ─── TWITTER / X ────────────────────────────────────────────────────────────
  {
    slug: 'twitter-video-download-free',
    title: 'Twitter Video Download Free',
    metaTitle: 'Twitter/X Video Download Free Online - HD | QuicklySave',
    metaDescription: 'Download Twitter/X videos for free in HD quality. Save any tweet video or GIF to your device online.',
    heading: 'Download Twitter Videos Free',
    subheading: 'Save Twitter/X videos and GIFs to your device. Free, fast, and in HD quality.',
    toolSlug: 'twitter-video-downloader',
    keywords: ['twitter video download', 'download tweet video', 'x video download free'],
  },
  {
    slug: 'download-twitter-video',
    title: 'Download Twitter Video',
    metaTitle: 'Download Twitter Video Online Free HD | QuicklySave',
    metaDescription: 'Download Twitter videos online for free. Save any Twitter/X video in HD quality instantly.',
    heading: 'Download Twitter Video Online',
    subheading: 'Paste any Twitter/X video URL and download it instantly. Free HD quality.',
    toolSlug: 'twitter-video-downloader',
    keywords: ['download twitter video', 'twitter video downloader', 'download x video'],
  },
  {
    slug: 'x-video-downloader',
    title: 'X Video Downloader',
    metaTitle: 'X Video Downloader Free Online - Download X.com Videos | QuicklySave',
    metaDescription: 'Download videos from X (Twitter) for free. Save any X video in HD quality online.',
    heading: 'X (Twitter) Video Downloader',
    subheading: 'Save videos from X.com instantly. Free, HD quality, no login required.',
    toolSlug: 'twitter-video-downloader',
    keywords: ['x video downloader', 'download x video', 'x.com video download'],
  },
  {
    slug: 'tweet-video-downloader',
    title: 'Tweet Video Downloader',
    metaTitle: 'Tweet Video Downloader Free Online HD | QuicklySave',
    metaDescription: 'Download tweet videos for free online. Save any Twitter/X tweet video in HD quality instantly.',
    heading: 'Tweet Video Downloader',
    subheading: 'Download any tweet video instantly. Free HD quality, no app needed.',
    toolSlug: 'twitter-video-downloader',
    keywords: ['tweet video downloader', 'download tweet video', 'twitter video save'],
  },
  {
    slug: 'twitter-gif-download',
    title: 'Twitter GIF Download',
    metaTitle: 'Twitter GIF Download Free Online | QuicklySave',
    metaDescription: 'Download GIFs from Twitter/X for free. Save any Twitter GIF as a video file online.',
    heading: 'Twitter GIF Download',
    subheading: 'Save Twitter/X GIFs to your device. Free, instant, no registration.',
    toolSlug: 'twitter-video-downloader',
    keywords: ['twitter gif download', 'download twitter gif', 'x gif downloader'],
  },

  // ─── FACEBOOK ───────────────────────────────────────────────────────────────
  {
    slug: 'facebook-video-download-free',
    title: 'Facebook Video Download Free',
    metaTitle: 'Facebook Video Download Free Online - HD | QuicklySave',
    metaDescription: 'Download Facebook videos for free in HD quality. Save any Facebook video to your device online.',
    heading: 'Download Facebook Videos Free',
    subheading: 'Save Facebook videos and Reels to your device. Free, fast, and in HD quality.',
    toolSlug: 'facebook-video-downloader',
    keywords: ['facebook video download', 'download fb video', 'facebook video download free'],
  },
  {
    slug: 'download-facebook-video',
    title: 'Download Facebook Video',
    metaTitle: 'Download Facebook Video Online Free HD | QuicklySave',
    metaDescription: 'Download Facebook videos online for free. Save any Facebook video in HD quality with one click.',
    heading: 'Download Facebook Video Online',
    subheading: 'Paste any Facebook video link and save it instantly. Free HD quality.',
    toolSlug: 'facebook-video-downloader',
    keywords: ['download facebook video', 'facebook video downloader', 'fb video download'],
  },
  {
    slug: 'fb-video-downloader',
    title: 'FB Video Downloader',
    metaTitle: 'FB Video Downloader Free Online HD | QuicklySave',
    metaDescription: 'Free FB video downloader. Download any Facebook video in HD quality online without any app.',
    heading: 'FB Video Downloader',
    subheading: 'Download Facebook videos in HD. Free, fast, no registration needed.',
    toolSlug: 'facebook-video-downloader',
    keywords: ['fb video downloader', 'facebook video download online', 'free facebook video downloader'],
  },
  {
    slug: 'facebook-reel-download',
    title: 'Facebook Reel Download',
    metaTitle: 'Facebook Reel Download Free Online HD | QuicklySave',
    metaDescription: 'Download Facebook Reels for free in HD quality. Save any Facebook Reel to your device online.',
    heading: 'Facebook Reel Download',
    subheading: 'Save Facebook Reels in HD quality. Free, instant, no login required.',
    toolSlug: 'facebook-video-downloader',
    keywords: ['facebook reel download', 'download facebook reel', 'fb reel downloader'],
  },

  // ─── GENERIC / ALL PLATFORMS ────────────────────────────────────────────────
  {
    slug: 'social-media-video-downloader',
    title: 'Social Media Video Downloader',
    metaTitle: 'Social Media Video Downloader - All Platforms Free | QuicklySave',
    metaDescription: 'Download videos from all social media platforms. Instagram, YouTube, TikTok, Twitter, Facebook. Free online tool.',
    heading: 'Social Media Video Downloader',
    subheading: 'One tool for all platforms. Download videos from Instagram, YouTube, TikTok, Twitter, and Facebook.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['social media video downloader', 'download social media video', 'all in one downloader'],
  },
  {
    slug: 'free-video-downloader-online',
    title: 'Free Video Downloader Online',
    metaTitle: 'Free Video Downloader Online - All Social Media | QuicklySave',
    metaDescription: 'Free online video downloader for all social media platforms. Download HD videos without registration.',
    heading: 'Free Video Downloader Online',
    subheading: 'Download videos from any social media platform for free. No registration needed.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['free video downloader', 'video downloader online', 'download video free'],
  },
  {
    slug: 'hd-video-downloader-online',
    title: 'HD Video Downloader Online',
    metaTitle: 'HD Video Downloader Online Free - All Platforms | QuicklySave',
    metaDescription: 'Download HD videos from Instagram, YouTube, TikTok, Twitter, and Facebook. Free online HD video downloader.',
    heading: 'HD Video Downloader Online',
    subheading: 'Download HD videos from all major social media platforms. Fast, free, and easy.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['hd video downloader', 'hd video download online', 'free hd downloader'],
  },
  {
    slug: 'video-downloader-no-watermark',
    title: 'Video Downloader No Watermark',
    metaTitle: 'Video Downloader No Watermark Free Online | QuicklySave',
    metaDescription: 'Download videos without watermark from TikTok, Instagram, and more. Free clean video downloader online.',
    heading: 'Video Downloader Without Watermark',
    subheading: 'Save clean videos without watermarks from TikTok, Instagram, and more. Free.',
    toolSlug: 'tiktok-no-watermark-downloader',
    keywords: ['video downloader no watermark', 'download without watermark', 'no watermark video downloader'],
  },
  {
    slug: 'online-video-downloader',
    title: 'Online Video Downloader',
    metaTitle: 'Online Video Downloader Free - All Sites | QuicklySave',
    metaDescription: 'Free online video downloader for Instagram, YouTube, TikTok, Twitter, and Facebook. No app needed.',
    heading: 'Online Video Downloader',
    subheading: 'Download videos from any platform online. No app or software needed.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['online video downloader', 'video download online', 'web video downloader'],
  },
  {
    slug: 'best-video-downloader-online',
    title: 'Best Video Downloader Online',
    metaTitle: 'Best Video Downloader Online Free 2025 | QuicklySave',
    metaDescription: 'The best free online video downloader in 2025. Download HD videos from Instagram, YouTube, TikTok, Twitter, and Facebook.',
    heading: 'Best Free Video Downloader Online',
    subheading: 'The #1 free online video downloader. HD quality, all platforms, no registration.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['best video downloader online', 'top video downloader', 'best free video downloader 2025'],
  },
  {
    slug: 'video-download-online-free',
    title: 'Video Download Online Free',
    metaTitle: 'Video Download Online Free HD No Registration | QuicklySave',
    metaDescription: 'Download videos online for free without registration. HD quality from all major social media platforms.',
    heading: 'Video Download Online Free',
    subheading: 'Free video downloads from all social platforms. No sign-up, no limits, HD quality.',
    toolSlug: 'youtube-video-downloader',
    keywords: ['video download online free', 'free video download no registration', 'download videos for free'],
  },
];

export function getSEOPageBySlug(slug: string): SEOPage | undefined {
  return seoPages.find((p) => p.slug === slug);
}
