import { Tool } from '@/types';

export const tools: Tool[] = [
  {
    slug: 'instagram-reels-downloader',
    title: 'Instagram Reels Downloader',
    description: 'Download Instagram Reels videos in HD quality. Save any Instagram Reel to your device for free.',
    metaTitle: 'Instagram Reels Downloader - Save Reels in HD | SnapPull',
    metaDescription: 'Download Instagram Reels in HD quality for free. Save any Instagram Reel video to your phone or computer instantly with SnapPull.',
    platform: 'instagram',
    icon: 'instagram',
    color: '#E4405F',
    placeholder: 'https://www.instagram.com/reel/...',
    features: [
      'Download Reels in original HD quality',
      'No login or account required',
      'Save directly to your device',
      'Works on iPhone, Android, and desktop',
    ],
    steps: [
      { number: 1, title: 'Copy the Reel link', description: 'Open Instagram and tap the share button on any Reel, then tap "Copy Link".' },
      { number: 2, title: 'Paste the link', description: 'Paste the copied link into the input field above.' },
      { number: 3, title: 'Download', description: 'Click the Download button and save the Reel to your device.' },
    ],
    faqs: [
      { question: 'How do I download Instagram Reels?', answer: 'Copy the Reel link from Instagram, paste it into SnapPull, and click Download. The video will be saved to your device in HD quality.' },
      { question: 'Is it free to download Instagram Reels?', answer: 'Yes, SnapPull is completely free to use. There are no hidden fees or subscriptions required.' },
      { question: 'Can I download Reels on my phone?', answer: 'Absolutely. SnapPull works on all devices including iPhone, Android phones, tablets, and desktop computers.' },
      { question: 'Do I need an Instagram account to download Reels?', answer: 'No, you do not need to log in or have an Instagram account to download public Reels.' },
    ],
  },
  {
    slug: 'instagram-video-downloader',
    title: 'Instagram Video Downloader',
    description: 'Download any Instagram video post in high quality. Save Instagram videos to your device instantly.',
    metaTitle: 'Instagram Video Downloader - Save Videos in HD | SnapPull',
    metaDescription: 'Download Instagram videos in HD quality for free. Save any Instagram video post to your phone or computer with SnapPull.',
    platform: 'instagram',
    icon: 'instagram',
    color: '#E4405F',
    placeholder: 'https://www.instagram.com/p/...',
    features: [
      'Download videos in original quality',
      'Support for all Instagram video posts',
      'Fast and free downloads',
      'No watermark added',
    ],
    steps: [
      { number: 1, title: 'Copy the video link', description: 'Open Instagram, go to the video post, tap the three dots, and select "Copy Link".' },
      { number: 2, title: 'Paste the link', description: 'Paste the copied URL into the input field above.' },
      { number: 3, title: 'Download', description: 'Click Download and save the video to your device.' },
    ],
    faqs: [
      { question: 'How do I download Instagram videos?', answer: 'Copy the video post link from Instagram, paste it into SnapPull, and click Download to save it.' },
      { question: 'What quality are downloaded videos?', answer: 'Videos are downloaded in their original uploaded quality, typically HD or Full HD.' },
      { question: 'Can I download private Instagram videos?', answer: 'No, SnapPull can only download videos from public Instagram accounts.' },
      { question: 'Is there a limit on downloads?', answer: 'No, there is no limit. You can download as many videos as you need.' },
    ],
  },
  {
    slug: 'instagram-photo-downloader',
    title: 'Instagram Photo Downloader',
    description: 'Download Instagram photos in full resolution. Save any Instagram image to your device.',
    metaTitle: 'Instagram Photo Downloader - Save Photos in Full Resolution | SnapPull',
    metaDescription: 'Download Instagram photos in full resolution for free. Save any Instagram image or carousel to your device with SnapPull.',
    platform: 'instagram',
    icon: 'instagram',
    color: '#E4405F',
    placeholder: 'https://www.instagram.com/p/...',
    features: [
      'Full resolution photo downloads',
      'Support for carousel posts',
      'No quality loss',
      'Instant download to device',
    ],
    steps: [
      { number: 1, title: 'Copy the photo link', description: 'Open Instagram, go to the photo post, and copy its link.' },
      { number: 2, title: 'Paste the link', description: 'Paste the copied URL into the input field.' },
      { number: 3, title: 'Download', description: 'Click Download to save the photo in full resolution.' },
    ],
    faqs: [
      { question: 'Can I download Instagram carousel photos?', answer: 'Yes, SnapPull supports downloading individual photos from carousel posts.' },
      { question: 'What format are photos saved in?', answer: 'Photos are saved in JPEG format at their original resolution.' },
      { question: 'Can I download profile pictures?', answer: 'Yes, you can download profile pictures in full resolution.' },
      { question: 'Are downloaded photos the same quality?', answer: 'Yes, photos are downloaded in the exact same quality as uploaded to Instagram.' },
    ],
  },
  {
    slug: 'instagram-audio-extractor',
    title: 'Instagram Audio Extractor',
    description: 'Extract audio from Instagram Reels and videos. Save Instagram audio as MP3 files.',
    metaTitle: 'Instagram Audio Extractor - Save Audio as MP3 | SnapPull',
    metaDescription: 'Extract audio from Instagram Reels and videos. Convert Instagram audio to MP3 and save to your device for free with SnapPull.',
    platform: 'instagram',
    icon: 'instagram',
    color: '#E4405F',
    placeholder: 'https://www.instagram.com/reel/...',
    features: [
      'Extract audio from Reels and videos',
      'Save as high-quality MP3',
      'Fast audio conversion',
      'Works with any Instagram video content',
    ],
    steps: [
      { number: 1, title: 'Copy the link', description: 'Copy the link of the Instagram Reel or video you want audio from.' },
      { number: 2, title: 'Paste the link', description: 'Paste the URL into the input field above.' },
      { number: 3, title: 'Extract audio', description: 'Click Download to extract and save the audio as an MP3 file.' },
    ],
    faqs: [
      { question: 'What format is the audio saved in?', answer: 'Audio is extracted and saved in MP3 format for maximum compatibility.' },
      { question: 'Can I extract audio from any Instagram video?', answer: 'Yes, you can extract audio from any public Instagram Reel or video post.' },
      { question: 'Is the audio quality good?', answer: 'The audio is extracted at the highest available quality from the source video.' },
      { question: 'Can I use extracted audio in my own content?', answer: 'Please check the original audio copyright before using it in your own content.' },
    ],
  },
  {
    slug: 'youtube-video-downloader',
    title: 'YouTube Video Downloader',
    description: 'Download YouTube videos in HD, Full HD, and 4K quality. Save any YouTube video for offline viewing.',
    metaTitle: 'YouTube Video Downloader - Save Videos in HD/4K | SnapPull',
    metaDescription: 'Download YouTube videos in HD, Full HD, or 4K quality for free. Save any YouTube video for offline viewing with SnapPull.',
    platform: 'youtube',
    icon: 'youtube',
    color: '#FF0000',
    placeholder: 'https://www.youtube.com/watch?v=...',
    features: [
      'Download in HD, Full HD, and 4K',
      'Multiple quality options',
      'Fast download speeds',
      'No registration required',
    ],
    steps: [
      { number: 1, title: 'Copy the YouTube URL', description: 'Go to YouTube, open the video you want, and copy the URL from the address bar.' },
      { number: 2, title: 'Paste the link', description: 'Paste the YouTube URL into the input field above.' },
      { number: 3, title: 'Choose quality and download', description: 'Select your preferred quality and click Download to save the video.' },
    ],
    faqs: [
      { question: 'What quality options are available?', answer: 'SnapPull offers multiple quality options including 360p, 720p HD, 1080p Full HD, and 4K when available.' },
      { question: 'Can I download YouTube Shorts?', answer: 'Yes, you can download YouTube Shorts the same way as regular videos.' },
      { question: 'Is it legal to download YouTube videos?', answer: 'Downloading YouTube videos for personal offline use is generally acceptable. Always respect copyright and creator rights.' },
      { question: 'How long does downloading take?', answer: 'Download time depends on video length and quality. Most videos download within seconds.' },
    ],
  },
  {
    slug: 'youtube-to-mp3',
    title: 'YouTube to MP3 Converter',
    description: 'Convert YouTube videos to MP3 audio files. Extract high-quality audio from any YouTube video.',
    metaTitle: 'YouTube to MP3 Converter - Extract Audio Free | SnapPull',
    metaDescription: 'Convert YouTube videos to MP3 audio files for free. Extract high-quality audio from any YouTube video with SnapPull.',
    platform: 'youtube',
    icon: 'youtube',
    color: '#FF0000',
    placeholder: 'https://www.youtube.com/watch?v=...',
    features: [
      'High-quality MP3 conversion',
      'Up to 320kbps audio quality',
      'Fast conversion speed',
      'Works with any YouTube video',
    ],
    steps: [
      { number: 1, title: 'Copy the YouTube URL', description: 'Find the YouTube video you want to convert and copy its URL.' },
      { number: 2, title: 'Paste the link', description: 'Paste the URL into the input field above.' },
      { number: 3, title: 'Convert and download', description: 'Click Download to convert the video to MP3 and save the audio file.' },
    ],
    faqs: [
      { question: 'What audio quality is available?', answer: 'SnapPull converts YouTube audio to MP3 at up to 320kbps, the highest standard MP3 quality.' },
      { question: 'Can I convert long videos?', answer: 'Yes, there is no length limit. You can convert videos of any duration.' },
      { question: 'Is the conversion fast?', answer: 'Yes, most conversions complete within seconds regardless of video length.' },
      { question: 'What file format is the output?', answer: 'Audio is saved in MP3 format, compatible with all devices and music players.' },
    ],
  },
  {
    slug: 'tiktok-video-downloader',
    title: 'TikTok Video Downloader',
    description: 'Download TikTok videos in HD quality. Save any TikTok video to your device for free.',
    metaTitle: 'TikTok Video Downloader - Save TikTok Videos HD | SnapPull',
    metaDescription: 'Download TikTok videos in HD quality for free. Save any TikTok video to your phone or computer with SnapPull.',
    platform: 'tiktok',
    icon: 'tiktok',
    color: '#000000',
    placeholder: 'https://www.tiktok.com/@user/video/...',
    features: [
      'HD quality downloads',
      'Fast and free',
      'Works on all devices',
      'No app installation needed',
    ],
    steps: [
      { number: 1, title: 'Copy the TikTok link', description: 'Open TikTok, tap Share on the video, and select "Copy Link".' },
      { number: 2, title: 'Paste the link', description: 'Paste the copied link into the input field above.' },
      { number: 3, title: 'Download', description: 'Click Download to save the TikTok video to your device.' },
    ],
    faqs: [
      { question: 'How do I copy a TikTok link?', answer: 'Open TikTok, find the video, tap the Share button (arrow icon), and tap "Copy Link".' },
      { question: 'Can I download TikTok videos on iPhone?', answer: 'Yes, SnapPull works perfectly on iPhone through Safari or any other browser.' },
      { question: 'Are downloads free?', answer: 'Yes, all downloads on SnapPull are completely free with no hidden costs.' },
      { question: 'Will the video have a watermark?', answer: 'Standard downloads may include the TikTok watermark. Use our no-watermark downloader for clean videos.' },
    ],
  },
  {
    slug: 'tiktok-no-watermark-downloader',
    title: 'TikTok No Watermark Downloader',
    description: 'Download TikTok videos without watermark. Save clean TikTok videos in HD quality.',
    metaTitle: 'TikTok No Watermark Downloader - Clean HD Videos | SnapPull',
    metaDescription: 'Download TikTok videos without watermark in HD quality. Save clean TikTok videos to your device for free with SnapPull.',
    platform: 'tiktok',
    icon: 'tiktok',
    color: '#000000',
    placeholder: 'https://www.tiktok.com/@user/video/...',
    features: [
      'No watermark on downloads',
      'Original HD quality',
      'Clean video output',
      'Free and unlimited',
    ],
    steps: [
      { number: 1, title: 'Copy the TikTok link', description: 'Open TikTok and copy the link of the video you want to download.' },
      { number: 2, title: 'Paste the link', description: 'Paste the URL into the input field above.' },
      { number: 3, title: 'Download without watermark', description: 'Click Download to save a clean version of the video without any watermark.' },
    ],
    faqs: [
      { question: 'How is the watermark removed?', answer: 'SnapPull fetches the original video source before the watermark is applied, giving you a clean download.' },
      { question: 'Is the quality the same without watermark?', answer: 'Yes, the video quality is identical. You get the original HD video without the watermark overlay.' },
      { question: 'Is it safe to download without watermark?', answer: 'Yes, SnapPull is completely safe. No software installation or account creation is required.' },
      { question: 'Can I use downloaded videos for editing?', answer: 'You can use downloaded videos for personal use. Always credit the original creator when reposting.' },
    ],
  },
  {
    slug: 'twitter-video-downloader',
    title: 'Twitter/X Video Downloader',
    description: 'Download Twitter/X videos in HD quality. Save any tweet video to your device.',
    metaTitle: 'Twitter/X Video Downloader - Save Tweet Videos | SnapPull',
    metaDescription: 'Download Twitter/X videos in HD quality for free. Save any tweet video or GIF to your device with SnapPull.',
    platform: 'twitter',
    icon: 'twitter',
    color: '#1DA1F2',
    placeholder: 'https://twitter.com/user/status/...',
    features: [
      'Download tweet videos in HD',
      'Support for GIF downloads',
      'Multiple quality options',
      'Works with twitter.com and x.com links',
    ],
    steps: [
      { number: 1, title: 'Copy the tweet link', description: 'Go to the tweet with the video, click Share, and select "Copy Link".' },
      { number: 2, title: 'Paste the link', description: 'Paste the tweet URL into the input field above.' },
      { number: 3, title: 'Download', description: 'Click Download to save the video to your device.' },
    ],
    faqs: [
      { question: 'Can I download videos from X.com?', answer: 'Yes, SnapPull works with both twitter.com and x.com links.' },
      { question: 'Can I download Twitter GIFs?', answer: 'Yes, Twitter GIFs are actually short videos and can be downloaded with SnapPull.' },
      { question: 'What quality options are available?', answer: 'Twitter videos are available in multiple qualities. SnapPull offers the highest available quality.' },
      { question: 'Do I need a Twitter account?', answer: 'No, you can download videos from public tweets without a Twitter account.' },
    ],
  },
  {
    slug: 'facebook-video-downloader',
    title: 'Facebook Video Downloader',
    description: 'Download Facebook videos in HD quality. Save any Facebook video to your device for free.',
    metaTitle: 'Facebook Video Downloader - Save FB Videos HD | SnapPull',
    metaDescription: 'Download Facebook videos in HD quality for free. Save any Facebook video to your phone or computer with SnapPull.',
    platform: 'facebook',
    icon: 'facebook',
    color: '#1877F2',
    placeholder: 'https://www.facebook.com/watch?v=...',
    features: [
      'HD and SD quality options',
      'Download public Facebook videos',
      'Fast processing',
      'No Facebook login required',
    ],
    steps: [
      { number: 1, title: 'Copy the video link', description: 'Go to the Facebook video, click the three dots, and select "Copy Link".' },
      { number: 2, title: 'Paste the link', description: 'Paste the Facebook video URL into the input field above.' },
      { number: 3, title: 'Download', description: 'Click Download to save the Facebook video to your device.' },
    ],
    faqs: [
      { question: 'Can I download Facebook Reels?', answer: 'Yes, SnapPull supports downloading Facebook Reels, Watch videos, and regular video posts.' },
      { question: 'Can I download private videos?', answer: 'No, SnapPull can only download videos from public Facebook posts and pages.' },
      { question: 'What quality is available?', answer: 'Facebook videos are available in SD and HD quality. SnapPull downloads the highest available quality.' },
      { question: 'Is it free?', answer: 'Yes, SnapPull is completely free. No registration or payment required.' },
    ],
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getToolsByPlatform(platform: string): Tool[] {
  return tools.filter((t) => t.platform === platform);
}

export const platforms = [
  { name: 'Instagram', slug: 'instagram', color: '#E4405F' },
  { name: 'YouTube', slug: 'youtube', color: '#FF0000' },
  { name: 'TikTok', slug: 'tiktok', color: '#000000' },
  { name: 'Twitter/X', slug: 'twitter', color: '#1DA1F2' },
  { name: 'Facebook', slug: 'facebook', color: '#1877F2' },
] as const;
